services:
  onedrop:
    image: onedrop-website
    container_name: onedrop-website
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=production
    networks:
      - custom_bridge

networks:
  custom_bridge:
    external: true
