services:
  onedrop:
    image: onedrop-website
    container_name: onedrop-website
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENVIRONMENT=production
    networks:
      custom_bridge:
        ipv4_address: 172.25.0.11

networks:
  custom_bridge:
    external: true
